version: "3.3"

services:

  ldap:
    image: osixia/openldap:stable
    entrypoint: [ "/container/tool/run", "--copy-service" ]
    ports:
      - "10389:389"
    environment:
      - LDAP_DOMAIN=evolveum.com
      - LDAP_ADMIN_PASSWORD=secret
      - LDAP_TLS=false
    networks:
      - iam-02-net
    volumes:
      - ldap_conf:/etc/ldap/slapd.d
      - ldap_data:/var/lib/ldap
      - ./ldap_files:/container/service/slapd/assets/config/bootstrap/ldif/custom/:ro

  midpoint_data:
    image: postgres:13-alpine
    environment:
     - POSTGRES_PASSWORD_FILE=/run/secrets/mp_database_password.txt
     - POSTGRES_USER=midpoint
     - POSTGRES_INITDB_ARGS=--lc-collate=en_US.utf8 --lc-ctype=en_US.utf8
    ports:
     - 5432:5432
    networks:
     - iam-02-net
    secrets:
     - mp_database_password.txt
    volumes:
     - midpoint_data:/var/lib/postgresql/data

  midpoint_server:
    build: ./midpoint_server/
    depends_on:
     - midpoint_data
    ports:
      - 8080:8080
    environment:
     - REPO_DATABASE_TYPE=postgresql
     - REPO_HOST=midpoint_data
     - REPO_DATABASE=midpoint
     - REPO_USER=midpoint
     - REPO_PASSWORD_FILE=/run/secrets/mp_database_password.txt
     - REPO_MISSING_SCHEMA_ACTION
     - REPO_UPGRADEABLE_SCHEMA_ACTION
     - REPO_SCHEMA_VERSION_IF_MISSING
     - REPO_SCHEMA_VARIANT
     - MP_KEYSTORE_PASSWORD_FILE=/run/secrets/mp_keystore_password.txt
     - MP_MEM_MAX
     - MP_MEM_INIT
     - MP_JAVA_OPTS
     - TZ
    networks:
     - iam-02-net
    secrets:
     - mp_database_password.txt
     - mp_keystore_password.txt
    volumes:
     - midpoint_home:/opt/midpoint/var

      - devsso-01

  josso:
    build: josso
    ports:
      - '8081:8081'
      - '8101:8101'
      - '5005:5005'
    environment:
        - JOSSO_CLIENT_ID=idbus-f2f7244e-bbce-44ca-8b33-f5c0bde339f7
        - JOSSO_CLIENT_SECRET=7oUHlv(HLT%vxK4L
        - JOSSO_ADMIN_USR=myadmin
        - JOSSO_ADMIN_PWD=changeme
        - JOSSO_SKIP_ADMIN_CREATE=false
        - KARAF_DEBUG=true
    networks:
      - iam-02-net
    depends_on:
      - ldap

  josso-wb:
    image: atricore/josso-wb:3.1.0-unstable
    ports:
      - '8082:8082'
    networks:
      - iam-02-net

  tomcat:
    build: tomcat
    ports:
      - '8180:8180'
    networks:
      - iam-02-net

networks:
  iam-02-net:    
    driver: bridge

secrets:
  mp_database_password.txt:
    file: ./configs-and-secrets/midpoint/database_password.txt
  mp_keystore_password.txt:
    file: ./configs-and-secrets/midpoint/keystore_password.txt
    
volumes:
  midpoint_data:
  midpoint_home:
  ldap_conf:
  ldap_data: